### ISSUE TITLE
Notes on the GraphQL Webinar

### ISSUE THREAD

**Issue by Urigo** [tocodeil/webinar-live-demos#125]
Thank you so much for creating a GraphQL one in Hebrew!

I would love to help in anyway we @the-guild-org can.

I guess just one note that I would make is to not use `express-graphql` (or at least tell people not to use it as they go into more real applications) as it is not maintained for many years and use one of the servers mentioned [here](https://graphql.org/code/#javascript-server) instead.
We of course recommend [Yoga](https://www.the-guild.dev/graphql/yoga-server/v3/comparison) that we maintain but there are other great options as well!

Also I would recommend to install graphql-tools scoped packages and not the full package (`@graphql-tools/schema`)

**Comment by ynonp** [comment]
Hi @Urigo and Thanks for the comments. Yoga looks really good and feature rich. I updated the video description in YouTube and added a link.

By the way - your work on GraphQL looks awesome. Would you be willing to teach a webinar demonstrating more advanced GraphQL features using yoga? (subscriptions, performance optimizations, caching, security, etc.)

**Comment by Urigo** [comment]
for sure!  thank you for your kind words
My email is on my profile so feel free to reach out for anything!

**Comment by ynonp** [comment]
Super and thanks! I'll email after the holiday with details
